# Generated by Django 2.0.13 on 2019-05-29 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_planets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Planets',
        ),
    ]
